### ISSUE TITLE
Need to render components according to the object getting from BE

### ISSUE THREAD

**Issue by Xaptured** [Xaptured/thejackfolio_dashboard#21]
Need to make changes for below sections to render based on objects that we get from backend

## Subtasks

- [ ] Render Organizations based on object getting from BE
- [ ] Render Instagram Posts based on object getting from BE
- [ ] Render YouTube videos based on object getting from BE
- [ ] Render Skills based on object getting from BE
